### ISSUE TITLE
html output option not available in v 0.3.3?

### ISSUE THREAD

**Issue by caonetto** [marschall-lab/panacus#79]
Hi, 
How can we generate the html report ouput that used to be available using the -o option in histgrowth?

Cheers.

**Comment by danydoerr** [comment]
It's still available, but we moved it into a separate command `panacus report` where you specify a yaml config for the calculations that you want panacus to perform. 

Here's an example 

```yaml
- !Histgrwoth
  name: testing this
  count_type: Bp
  graph: /path/to/graph
```
